In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv('/content/sample_data/Social_Network_Ads.csv')

In [ ]:
data=pd.get_dummies(data)

In [ ]:
data

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0              0            1
1    15810944   35            20000          0              0            1
2    15668575   26            43000          0              1            0
3    15603246   27            57000          0              1            0
4    15804002   19            76000          0              0            1
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1              1            0
396  15706071   51            23000          1              0            1
397  15654296   50            20000          1              1            0
398  15755018   36            33000          0              0            1
399  15594041   49            36000          1              1            0

[400 rows x 6 columns]

In [ ]:
data['User ID'].nunique()

400

In [ ]:
x=data.drop(['User ID','Purchased'],axis=1)

In [ ]:
y=data['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_clf=SVC(kernel='rbf')

In [ ]:
svm_clf.fit(x_train,y_train)

SVC()

In [ ]:
y_pred=svm_clf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[60,  3],
       [22, 15]])

In [ ]:
accuracy_score(y_test,y_pred)

0.75

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt_clf=DecisionTreeClassifier(random_state=42)

In [ ]:
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred=dt_clf.predict(x_test)


In [ ]:
confusion_matrix(y_test,y_pred)

array([[56,  7],
       [ 9, 28]])

In [ ]:
accuracy_score(y_test,y_pred)

0.84

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier()
rf_clf.fit(x_train,y_train)
y_pred=rf_clf.predict(x_test)

In [ ]:
confusion_matrix(y_test,y_pred)

array([[57,  6],
       [ 5, 32]])

In [ ]:
accuracy_score(y_test,y_pred)

0.89